# Rubocop version is locked in the dependencies of scc-codestyle gem.
# The version of scc-codestyle gem is specified in the Dockerfile.
inherit_gem:
  scc-codestyle:
    - default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Gemfile
    - config.ru
  Exclude:
    - .bundle/**/*
    - vendor/**/*
    - package/*
    - Rakefile

Rails:
  Enabled: false

# Impossible to satisfy these rules in specs
RSpec/ExpectInHook:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

# disabled, %<> should not be used in translatable strings
# but otherwise it does not matter much
Style/FormatStringToken:
  Enabled: false
